### ISSUE TITLE
Cannot interact with villagers

### ISSUE THREAD

**Issue by Aersoldorf** [G3rste/vsvillage#2]
I have found several structures with villagers in them, but none of the villagers will interact with me. I've tried right clicking on them to talk to them but nothing happens. Am I doing something wrong?

**Comment by G3rste** [comment]
No you are doint nothing wrong.
Interacting with villagers is simply not implemented yet :)

**Comment by G3rste** [comment]
With VSQuest there is now the possibility to interact with villagers
