### ISSUE TITLE
[Error] [vsvillage] An exception was thrown when trying to start the mod

### ISSUE THREAD

**Issue by Taiwendo** [G3rste/vsvillage#6]
Server v1.17.0-pre.4, network v1.17.4, api v1.7.0

Okay Server start with new version with lot of errors =/
[server-event.txt](https://github.com/G3rste/vsvillage/files/9127913/server-event.txt)

**Comment by G3rste** [comment]
Whoops sry forgot to release the new vs quest version 
Can you check if this helps: https://mods.vintagestory.at/download?fileid=6553
